/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangunruang;

/**
 *
 * @author Andreditvir
 */
public class InputBalokFrame extends javax.swing.JFrame {

    /**
     * Creates new form CobaFrame
     */
    public InputBalokFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputTextBoxPanjangBalok = new javax.swing.JTextField();
        inputTextBoxLebarBalok = new javax.swing.JTextField();
        JudulProgram = new javax.swing.JLabel();
        InputBalokJudulTextBox = new javax.swing.JLabel();
        tombolMenuInputBalok = new javax.swing.JButton();
        labelPanjangBalok = new javax.swing.JLabel();
        labelLebarBalok = new javax.swing.JLabel();
        inputTextBoxTinggiBalok = new javax.swing.JTextField();
        labelTinggiBalok = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JudulProgram.setText("Program Java : Bangun Ruang");

        InputBalokJudulTextBox.setText("-= Input Balok =-");

        tombolMenuInputBalok.setText("Selesai");
        tombolMenuInputBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolMenuInputBalokActionPerformed(evt);
            }
        });

        labelPanjangBalok.setText("Panjang");

        labelLebarBalok.setText("Lebar");

        labelTinggiBalok.setText("Tinggi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPanjangBalok, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelLebarBalok, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTinggiBalok, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JudulProgram)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputBalokJudulTextBox)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(inputTextBoxLebarBalok, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(inputTextBoxPanjangBalok, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(tombolMenuInputBalok)
                                .addComponent(inputTextBoxTinggiBalok, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(97, 97, 97))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JudulProgram)
                .addGap(18, 18, 18)
                .addComponent(InputBalokJudulTextBox)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputTextBoxPanjangBalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPanjangBalok))
                                .addGap(18, 18, 18)
                                .addComponent(inputTextBoxLebarBalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelLebarBalok))
                        .addGap(18, 18, 18)
                        .addComponent(inputTextBoxTinggiBalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelTinggiBalok))
                .addGap(32, 32, 32)
                .addComponent(tombolMenuInputBalok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolMenuInputBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolMenuInputBalokActionPerformed
        BangunRuang balok = new Balok();
        BangunRuang bangunRuang;
        ViewDasar input = new ViewDasarInput("Input Form Balok",balok);
        int panjang = Integer.parseInt(inputTextBoxPanjangBalok.getText());
        int lebar = Integer.parseInt(inputTextBoxLebarBalok.getText());
        int tinggi = Integer.parseInt(inputTextBoxTinggiBalok.getText());
        bangunRuang = new Balok(panjang, lebar, tinggi);
        this.dispose();
        new MenuUtamaFrame().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_tombolMenuInputBalokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputBalokFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputBalokFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputBalokFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputBalokFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputBalokFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InputBalokJudulTextBox;
    private javax.swing.JLabel JudulProgram;
    private javax.swing.JTextField inputTextBoxLebarBalok;
    private javax.swing.JTextField inputTextBoxPanjangBalok;
    private javax.swing.JTextField inputTextBoxTinggiBalok;
    private javax.swing.JLabel labelLebarBalok;
    private javax.swing.JLabel labelPanjangBalok;
    private javax.swing.JLabel labelTinggiBalok;
    private javax.swing.JButton tombolMenuInputBalok;
    // End of variables declaration//GEN-END:variables

    void setInvicible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
